version: 4.0.9
#监听IP
IP: 0.0.0.0
#监听端口
PORT: 27120

#基准目录
base_dir: /tmp/mongodb-quzl2


#配置文件目录
config_file: "{{ base_dir }}/mongod.config"
#数据目录
data_dir: "{{ base_dir }}/data"
# pid目录
pid_file: "{{ base_dir }}/mongo.pid"
#日志文件
log_file: "{{ base_dir }}/mongod.log"


#内存限制GB
mem_size: 1

#管理员账号
root_user_name: admin
#管理员密码：
root_user_passwd: f1b452c26016f6363
#只读账号
read_user_name: read
#只读账号密码
read_user_passwd: a8b5908793b6e
